### ISSUE TITLE
Add profile page

### ISSUE THREAD

**Issue by KhanMaytok** [KhanMaytok/maytok#4]
Create UI for profiles

**Comment by Nitish18** [comment]
@KhanMaytok  Can I work on this ??
Can you tell little more details about the Issue.

**Comment by KhanMaytok** [comment]
The profile image now is:

![image](https://cloud.githubusercontent.com/assets/5711547/19200680/f17cb33e-8c8f-11e6-9b59-80cbfc7bbca9.png)

Maybe add some very basic UI improvement.

The profile page is at https://github.com/KhanMaytok/maytok/blob/master/app/Resources/FOSUserBundle/views/Profile/show_content.html.twig

**Comment by victorvh845** [comment]
#7
